---
title: "Tidy Tuesday 2025-03-11"
format: html
editor: visual
author: Sebastian Stefanowicz
---

```{r message=FALSE}
# Load Packages
library(tidyverse)
library(tidytuesdayR)
library(pixarfilms)
library(patchwork)
```

```{r load data}
# Load Data
pixar_films <- pixarfilms::pixar_films |>
  dplyr::mutate(
    dplyr::across(
      c("number", "run_time"),
      as.integer
    )
  )
public_response <- pixarfilms::public_response |>
  dplyr::mutate(
    dplyr::across(
      c("rotten_tomatoes", "metacritic", "critics_choice"),
      as.integer
    )
  )
```

```{r wrangling}
# Join datasets and filter to include films from 2020 and earlier (since more recent films do not have public/critical reception values)
pixar_films_combined <- left_join(pixar_films, public_response, by = "film") %>% filter(release_date < "2021-01-01")

# Translate cinema scores of A+, A, and A- to 100, 95, and 90 respectively. Then average all rotten tomatoes, metacritic, cinema score, and critics choice scores.
as_factor(pixar_films_combined$cinema_score)

pixar_films_combined <- pixar_films_combined %>% mutate(cinema_score_numeric = case_when(
  cinema_score == "A+" ~ 100,
  cinema_score == "A"  ~ 95,
  cinema_score == "A-" ~ 90),
  ave_score = rowMeans(across(c(cinema_score_numeric, metacritic, rotten_tomatoes, critics_choice)), na.rm = TRUE)
)
```

```{r viz, fig.width = 8, fig.height = 5.5}
# Scatterplot of public reception over time combined with a small geom_segment to help visualize the frequency of releases
score_plot <- ggplot(pixar_films_combined, aes(x = release_date, y = ave_score)) +
  geom_point(color = "gray25") +
  geom_text(aes(label = film), size = 2.8, vjust = .5, hjust = -.15, color = "gray25") +
  labs(title = "Public Reception of Pixar Films over Time", x = "Release Date", y = "Audience and Critic Reception") +
  theme_minimal() +
  theme(axis.text.x = element_blank())

release_plot <- ggplot(pixar_films_combined, aes(x = release_date)) +
  geom_segment(aes(xend = release_date, y = 0, yend = 1), linewidth = 0.8, color = "gray25") +
  labs(x = "Frequency of Releases", y = NULL, caption = "Note: Public Reception Score is a simple average of Metacritic, Cinema Score, Rotten Tomatoes, and Critics Choice scores") +
  theme_minimal() +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

combined_plot <- score_plot / release_plot + plot_layout(heights = c(1, 0.07), guides = "collect")

combined_plot
```
